import type {
  HorizonSpriteId,
  HorizonSpriteSpec,
  SatelliteSpriteId,
  SatelliteSpriteSpec,
  ShipPackId,
  ShipSpriteSpec,
  ThemeDefinition,
  VisualVariant,
  WorldThemeId,
} from "./types";

export const SHIP_SPRITES: Record<ShipPackId, ShipSpriteSpec> = {
  runner: {
    sprite: [
      "..22..",
      ".2112.",
      "211112",
      "..33..",
    ],
    sizeRange: [1.35, 2.1],
    speedRange: [18, 38],
    trailRange: [2, 6],
  },
  barge: {
    sprite: [
      "...222...",
      "..21112..",
      ".2111112.",
      "211111112",
      "..34443..",
    ],
    sizeRange: [1.8, 2.5],
    speedRange: [12, 24],
    trailRange: [0, 1],
  },
  probe: {
    sprite: [
      "...2...",
      "..212..",
      ".21112.",
      "..3.3..",
    ],
    sizeRange: [1.1, 1.6],
    speedRange: [24, 46],
    trailRange: [4, 8],
  },
  diamond: {
    sprite: [
      "...2...",
      "..212..",
      ".21412.",
      "..343..",
    ],
    sizeRange: [1.25, 1.9],
    speedRange: [18, 34],
    trailRange: [3, 7],
  },
  manta: {
    sprite: [
      ".22..22.",
      "22111222",
      "..2112..",
      "...33...",
    ],
    sizeRange: [1.5, 2.2],
    speedRange: [16, 30],
    trailRange: [1, 4],
  },
  frigate: {
    sprite: [
      "....2....",
      "...212...",
      "..21112..",
      ".2111112.",
      "211141112",
      "...3.3...",
    ],
    sizeRange: [1.7, 2.35],
    speedRange: [14, 26],
    trailRange: [0, 2],
  },
  shuttle: {
    sprite: [
      "..222..",
      ".21112.",
      "2114112",
      "..3.3..",
    ],
    sizeRange: [1.3, 1.95],
    speedRange: [20, 34],
    trailRange: [1, 3],
  },
  wisp: {
    sprite: [
      "...2...",
      "..242..",
      "...2...",
      "..3.3..",
    ],
    sizeRange: [1.05, 1.45],
    speedRange: [28, 52],
    trailRange: [5, 9],
  },
  skiff: {
    sprite: [
      "..22...",
      ".2112..",
      "211412.",
      "..3.3..",
    ],
    sizeRange: [1.15, 1.7],
    speedRange: [26, 44],
    trailRange: [4, 7],
  },
  hauler: {
    sprite: [
      "...2222...",
      "..211112..",
      ".21111112.",
      "2111111112",
      "...3443...",
    ],
    sizeRange: [1.9, 2.7],
    speedRange: [10, 22],
    trailRange: [0, 1],
  },
  spire: {
    sprite: [
      "...2...",
      "..242..",
      ".21412.",
      "..121..",
      "..3.3..",
    ],
    sizeRange: [1.25, 1.8],
    speedRange: [20, 36],
    trailRange: [2, 5],
  },
};

export const SATELLITE_SPRITES: Record<SatelliteSpriteId, SatelliteSpriteSpec> = {
  relay: {
    sprite: [
      "..2..",
      "21112",
      "..3..",
    ],
    sizeRange: [1, 1.6],
    speedRange: [10, 24],
  },
  dish: {
    sprite: [
      ".222.",
      "..1..",
      ".131.",
    ],
    sizeRange: [1.05, 1.65],
    speedRange: [10, 22],
  },
  kite: {
    sprite: [
      "..2..",
      ".212.",
      "..3..",
    ],
    sizeRange: [0.95, 1.4],
    speedRange: [14, 28],
  },
  shard: {
    sprite: [
      "..2",
      ".21",
      "213",
    ],
    sizeRange: [0.9, 1.3],
    speedRange: [18, 32],
  },
  lantern: {
    sprite: [
      "..2..",
      ".242.",
      "..3..",
    ],
    sizeRange: [1.05, 1.55],
    speedRange: [8, 18],
  },
  solar: {
    sprite: [
      "..2..",
      "21412",
      "..3..",
    ],
    sizeRange: [1.1, 1.7],
    speedRange: [10, 20],
  },
  drifter: {
    sprite: [
      "...2...",
      "..212..",
      ".21112.",
      "..3.3..",
    ],
    sizeRange: [0.95, 1.45],
    speedRange: [16, 30],
  },
  cluster: {
    sprite: [
      ".2.2.",
      "21312",
      ".3.3.",
    ],
    sizeRange: [1, 1.5],
    speedRange: [12, 24],
  },
};

export const HORIZON_SPRITES: Record<HorizonSpriteId, HorizonSpriteSpec> = {
  relay_spire: {
    sprite: [
      "...2...",
      "...1...",
      "..111..",
      "...1...",
      "..141..",
      "...1...",
      "..111..",
    ],
    scaleRange: [1.4, 2.3],
    layerBias: 0,
  },
  dish_array: {
    sprite: [
      ".22222.",
      "..111..",
      ".11111.",
      "...1...",
      "..131..",
    ],
    scaleRange: [1.5, 2.2],
    layerBias: 1,
  },
  signal_gate: {
    sprite: [
      "2.....2",
      "11...11",
      "11...11",
      "1144411",
      "1111111",
    ],
    scaleRange: [1.6, 2.5],
    layerBias: 0,
  },
  antenna_tripod: {
    sprite: [
      "...2...",
      "...1...",
      "..111..",
      ".1.3.1.",
      "1.....1",
    ],
    scaleRange: [1.3, 2.1],
    layerBias: 0,
  },
  monolith_gate: {
    sprite: [
      "11...11",
      "11...11",
      "11.4.11",
      "11...11",
      "1111111",
    ],
    scaleRange: [1.8, 2.8],
    layerBias: 0,
  },
  citadel_wall: {
    sprite: [
      "111111111",
      "122111221",
      "111444111",
      "111111111",
    ],
    scaleRange: [1.5, 2.4],
    layerBias: 1,
  },
  ruin_arch: {
    sprite: [
      "11...11",
      "11...11",
      "111.111",
      "1.....1",
      "11...11",
    ],
    scaleRange: [1.6, 2.4],
    layerBias: 1,
  },
  buried_dome: {
    sprite: [
      "..222..",
      ".21112.",
      "2111112",
      ".11111.",
    ],
    scaleRange: [1.5, 2.3],
    layerBias: 1,
  },
  crystal_fan: {
    sprite: [
      "..2.2..",
      ".22422.",
      "..242..",
      ".21112.",
      "..111..",
    ],
    scaleRange: [1.5, 2.4],
    layerBias: 0,
  },
  crystal_pylon: {
    sprite: [
      "...2...",
      "..242..",
      "..212..",
      "..111..",
      ".11111.",
    ],
    scaleRange: [1.4, 2.2],
    layerBias: 0,
  },
  refinery_stack: {
    sprite: [
      "....2....",
      "...111...",
      "...141...",
      "...111...",
      "..11111..",
      ".1111111.",
    ],
    scaleRange: [1.7, 2.5],
    layerBias: 0,
  },
  quarry_rig: {
    sprite: [
      "2.....2",
      "11...11",
      ".11111.",
      "..141..",
      ".11111.",
      "11...11",
    ],
    scaleRange: [1.7, 2.6],
    layerBias: 1,
  },
  shrine_gate: {
    sprite: [
      "..222..",
      ".21112.",
      "11...11",
      "11.4.11",
      "1111111",
    ],
    scaleRange: [1.6, 2.4],
    layerBias: 0,
  },
  lantern_spires: {
    sprite: [
      "2...2...2",
      "1...1...1",
      "1.4.1.4.1",
      "1...1...1",
      "11.111.11",
    ],
    scaleRange: [1.4, 2.1],
    layerBias: 0,
  },
  dock_towers: {
    sprite: [
      "2.......2",
      "11.....11",
      "11.222.11",
      "11.111.11",
      "111111111",
    ],
    scaleRange: [1.5, 2.3],
    layerBias: 0,
  },
  orbital_lift: {
    sprite: [
      "...2...",
      "...1...",
      "...1...",
      "..141..",
      "..111..",
      ".11111.",
    ],
    scaleRange: [1.6, 2.4],
    layerBias: 0,
  },
  vault_steps: {
    sprite: [
      "...2...",
      "..111..",
      ".11111.",
      "1114111",
      "1111111",
    ],
    scaleRange: [1.6, 2.5],
    layerBias: 1,
  },
  scanner_grid: {
    sprite: [
      "2.2.2.2",
      "11111111",
      "1.4..4.1",
      "11111111",
    ],
    scaleRange: [1.5, 2.2],
    layerBias: 1,
  },
  wave_temple: {
    sprite: [
      "..222..",
      ".21112.",
      "2114112",
      ".11111.",
      "11...11",
    ],
    scaleRange: [1.5, 2.3],
    layerBias: 0,
  },
  bone_field: {
    sprite: [
      "2..2..2",
      "11.11.11",
      ".11111.",
      "11...11",
    ],
    scaleRange: [1.4, 2.2],
    layerBias: 1,
  },
};

export const WORLD_THEMES: Record<WorldThemeId, ThemeDefinition> = {
  relay: {
    terrainStyles: ["ridges", "mesas"],
    weatherModes: ["crosswind", "sparse-rain", "comet-field"],
    celestialModes: ["ringed-planet", "moon", "gas-giant"],
    shipPacks: ["probe", "runner", "shuttle", "skiff"],
    satelliteSprites: ["relay", "dish", "kite", "solar"],
    horizonSprites: ["relay_spire", "dish_array", "signal_gate", "antenna_tripod", "lantern_spires", "scanner_grid"],
    skyFeatures: ["satellite", "data-arc", "signal-ladder", "constellation"],
  },
  citadel: {
    terrainStyles: ["crags", "mesas", "ridges"],
    weatherModes: ["meteor-shower", "comet-field", "crosswind"],
    celestialModes: ["moon", "ringed-planet", "gas-giant"],
    shipPacks: ["frigate", "barge", "diamond", "hauler"],
    satelliteSprites: ["relay", "shard", "solar"],
    horizonSprites: ["monolith_gate", "citadel_wall", "signal_gate", "relay_spire", "orbital_lift"],
    skyFeatures: ["constellation", "data-arc", "satellite"],
  },
  sanctum: {
    terrainStyles: ["mesas", "dunes", "ridges"],
    weatherModes: ["comet-field", "sparse-rain"],
    celestialModes: ["twin-moons", "moon", "ringed-planet"],
    shipPacks: ["diamond", "wisp", "shuttle", "spire"],
    satelliteSprites: ["lantern", "kite", "cluster"],
    horizonSprites: ["shrine_gate", "lantern_spires", "crystal_pylon", "monolith_gate", "vault_steps"],
    skyFeatures: ["constellation", "signal-ladder", "data-arc"],
  },
  quarry: {
    terrainStyles: ["mesas", "crags", "ridges"],
    weatherModes: ["crosswind", "sparse-rain", "meteor-shower"],
    celestialModes: ["moon", "gas-giant", "none"],
    shipPacks: ["barge", "runner", "shuttle", "hauler"],
    satelliteSprites: ["dish", "relay", "drifter"],
    horizonSprites: ["quarry_rig", "refinery_stack", "buried_dome", "antenna_tripod", "scanner_grid"],
    skyFeatures: ["satellite", "signal-ladder", "constellation"],
  },
  reef: {
    terrainStyles: ["dunes", "ridges", "mesas"],
    weatherModes: ["comet-field", "crosswind", "sparse-rain"],
    celestialModes: ["ringed-planet", "twin-moons", "moon"],
    shipPacks: ["manta", "wisp", "probe", "skiff"],
    satelliteSprites: ["kite", "lantern", "shard", "cluster"],
    horizonSprites: ["crystal_fan", "crystal_pylon", "buried_dome", "lantern_spires", "wave_temple"],
    skyFeatures: ["constellation", "data-arc", "satellite"],
  },
  graveyard: {
    terrainStyles: ["crags", "ridges", "mesas"],
    weatherModes: ["sparse-rain", "crosswind", "meteor-shower"],
    celestialModes: ["none", "moon", "twin-moons"],
    shipPacks: ["wisp", "frigate", "probe", "spire"],
    satelliteSprites: ["shard", "relay", "drifter"],
    horizonSprites: ["ruin_arch", "monolith_gate", "citadel_wall", "relay_spire", "bone_field"],
    skyFeatures: ["constellation", "signal-ladder"],
  },
  harbor: {
    terrainStyles: ["dunes", "ridges", "mesas"],
    weatherModes: ["sparse-rain", "comet-field", "crosswind"],
    celestialModes: ["moon", "ringed-planet", "gas-giant"],
    shipPacks: ["shuttle", "runner", "manta", "skiff"],
    satelliteSprites: ["dish", "kite", "lantern", "solar"],
    horizonSprites: ["buried_dome", "dish_array", "signal_gate", "shrine_gate", "relay_spire", "dock_towers"],
    skyFeatures: ["satellite", "constellation", "data-arc"],
  },
  watchtower: {
    terrainStyles: ["ridges", "mesas", "crags"],
    weatherModes: ["crosswind", "comet-field", "meteor-shower"],
    celestialModes: ["gas-giant", "moon", "ringed-planet"],
    shipPacks: ["skiff", "frigate", "shuttle", "probe"],
    satelliteSprites: ["solar", "relay", "dish", "cluster"],
    horizonSprites: ["dock_towers", "orbital_lift", "scanner_grid", "relay_spire", "signal_gate"],
    skyFeatures: ["satellite", "data-arc", "constellation", "signal-ladder"],
  },
  catacomb: {
    terrainStyles: ["crags", "ridges"],
    weatherModes: ["sparse-rain", "meteor-shower", "crosswind"],
    celestialModes: ["none", "twin-moons", "moon"],
    shipPacks: ["wisp", "spire", "probe", "frigate"],
    satelliteSprites: ["shard", "drifter", "relay"],
    horizonSprites: ["bone_field", "vault_steps", "ruin_arch", "monolith_gate", "citadel_wall"],
    skyFeatures: ["constellation", "signal-ladder", "data-arc"],
  },
  mirage: {
    terrainStyles: ["dunes", "mesas", "ridges"],
    weatherModes: ["comet-field", "sparse-rain", "crosswind"],
    celestialModes: ["ringed-planet", "twin-moons", "moon"],
    shipPacks: ["manta", "skiff", "diamond", "spire"],
    satelliteSprites: ["lantern", "solar", "kite", "cluster"],
    horizonSprites: ["wave_temple", "crystal_fan", "shrine_gate", "buried_dome", "lantern_spires"],
    skyFeatures: ["constellation", "satellite", "data-arc"],
  },
};

export const VARIANT_THEME_POOLS: Record<VisualVariant, WorldThemeId[]> = {
  neon: ["citadel", "relay", "reef", "graveyard", "sanctum", "watchtower", "catacomb"],
  accent: ["relay", "citadel", "sanctum", "harbor", "reef", "quarry", "watchtower", "mirage"],
  glassy: ["harbor", "reef", "relay", "sanctum", "quarry", "mirage"],
  minimal: ["graveyard", "harbor", "relay", "quarry", "reef", "catacomb", "mirage"],
};
